# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/romset/ip/romset_ansa_0/romset_ansa_0.xci
# IP: The module: 'romset_ansa_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/romset/ip/romset_ansa_0/romset_ansa_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'romset_ansa_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/romset/ip/romset_ansa_0/romset_ansa_0.xci
# IP: The module: 'romset_ansa_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/romset/ip/romset_ansa_0/romset_ansa_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'romset_ansa_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
