# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/r1/ip/r1_dist_mem_gen_0_0/r1_dist_mem_gen_0_0.xci
# IP: The module: 'r1_dist_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/r1/ip/r1_dist_mem_gen_0_0/r1_dist_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'r1_dist_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/r1/ip/r1_dist_mem_gen_0_0/r1_dist_mem_gen_0_0.xci
# IP: The module: 'r1_dist_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/r1/ip/r1_dist_mem_gen_0_0/r1_dist_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'r1_dist_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
