# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/r1/r1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==r1 || ORIG_REF_NAME==r1} -quiet] -quiet

# IP: bd/r1/ip/r1_dist_mem_gen_0_0/r1_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==r1_dist_mem_gen_0_0 || ORIG_REF_NAME==r1_dist_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/romset/romset.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==romset || ORIG_REF_NAME==romset} -quiet] -quiet

# IP: bd/romset/ip/romset_dist_mem_gen_0_0/romset_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==romset_dist_mem_gen_0_0 || ORIG_REF_NAME==romset_dist_mem_gen_0_0} -quiet] -quiet

# IP: bd/romset/ip/romset_dist_mem_gen_0_1/romset_dist_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==romset_dist_mem_gen_0_1 || ORIG_REF_NAME==romset_dist_mem_gen_0_1} -quiet] -quiet

# IP: bd/romset/ip/romset_ansa_0/romset_ansa_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==romset_ansa_0 || ORIG_REF_NAME==romset_ansa_0} -quiet] -quiet

# IP: bd/romset/ip/romset_ansb_0/romset_ansb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==romset_ansb_0 || ORIG_REF_NAME==romset_ansb_0} -quiet] -quiet

# IP: bd/romset/ip/romset_dist_mem_gen_0_2/romset_dist_mem_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==romset_dist_mem_gen_0_2 || ORIG_REF_NAME==romset_dist_mem_gen_0_2} -quiet] -quiet

# IP: bd/romset/ip/romset_dist_mem_gen_0_3/romset_dist_mem_gen_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==romset_dist_mem_gen_0_3 || ORIG_REF_NAME==romset_dist_mem_gen_0_3} -quiet] -quiet

# XDC: bd/r1/r1_ooc.xdc

# XDC: bd/romset/romset_ooc.xdc
