# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/84546/Desktop/main/HDMI_output_test.cache/wt [current_project]
set_property parent.project_path C:/Users/84546/Desktop/main/HDMI_output_test.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
add_files C:/Users/84546/Desktop/main/reading_data.coe
add_files C:/Users/84546/Desktop/main/HDMI_output_test.srcs/title.coe
add_files C:/Users/84546/Desktop/main/HDMI_output_test.srcs/ansa.coe
add_files C:/Users/84546/Desktop/main/HDMI_output_test.srcs/ansb.coe
add_files C:/Users/84546/Desktop/main/HDMI_output_test.srcs/ansc.coe
add_files C:/Users/84546/Desktop/main/HDMI_output_test.srcs/hard.coe
add_files C:/Users/84546/Desktop/main/HDMI_output_test.srcs/ans.coe
add_files C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/ans.coe
add_files C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/ansa.coe
add_files C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/ansb.coe
add_files C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/hard.coe
add_files C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/title.coe
add_files C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/ansc.coe
add_files c:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/xxx/title.coe
read_verilog -library xil_defaultlib {
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/new/CounterToAscii.v
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/CtrlLogic.v
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/new/JudgeHighest.v
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/Key_Store.v
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/LED_Ctrl.v
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/Logic_Top.v
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/Point_adder.v
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/new/Score2ASC.v
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/new/Trans.v
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/counter_60.v
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/r1/hdl/r1_wrapper.v
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/romset/hdl/romset_wrapper.v
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/show_design.v
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/imports/sources_1/top.v
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/new/top_design.v
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/new/Logic_Show_Top.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/imports/src/SyncAsync.vhd
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/imports/src/SyncAsyncReset.vhd
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/imports/src/ClockGen.vhd
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/imports/src/DVI_Constants.vhd
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/imports/src/OutputSERDES.vhd
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/imports/src/TMDS_Encoder.vhd
  C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/imports/src/rgb2dvi.vhd
}
add_files C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/r1/r1.bd
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/r1/ip/r1_dist_mem_gen_0_0/r1_dist_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/r1/r1_ooc.xdc]

add_files C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/romset/romset.bd
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/romset/ip/romset_dist_mem_gen_0_0/romset_dist_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/romset/ip/romset_dist_mem_gen_0_1/romset_dist_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/romset/ip/romset_ansa_0/romset_ansa_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/romset/ip/romset_ansb_0/romset_ansb_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/romset/ip/romset_dist_mem_gen_0_2/romset_dist_mem_gen_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/romset/ip/romset_dist_mem_gen_0_3/romset_dist_mem_gen_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/bd/romset/romset_ooc.xdc]

read_ip -quiet C:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/ip/video_pll/video_pll.xci
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/ip/video_pll/video_pll_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/ip/video_pll/video_pll.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84546/Desktop/main/HDMI_output_test.srcs/sources_1/ip/video_pll/video_pll_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/84546/Desktop/main/HDMI_output_test.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files C:/Users/84546/Desktop/main/HDMI_output_test.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Logic_Show_Top -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Logic_Show_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Logic_Show_Top_utilization_synth.rpt -pb Logic_Show_Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
